name: Lighthouse CI

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: "0 2 * * *" # nightly at 2am UTC
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Start app
        run: nohup npm run start -- -p 8080 &

      - name: Wait for server
        run: |
          n=0
          until curl -sSf http://localhost:8080 >/dev/null || [ $n -ge 15 ]; do
            n=$((n+1))
            echo "waiting for server... ($n)"
            sleep 1
          done

      - name: Install Lighthouse
        run: npm i -g lighthouse@13

      - name: Run Lighthouse
        run: |
          lighthouse http://localhost:8080 --output=json --output-path=./lighthouse-report.json --chrome-flags='--headless --no-sandbox'

      - name: Generate summary & check thresholds
        id: summary
        run: |
          node ./tools/lh-summary.js
          echo "summary_file=lighthouse-summary.md" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: |
            ./lighthouse-report.json
            ./lighthouse-summary.md

      - name: Post or update PR comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            $(cat ./lighthouse-summary.md)
